apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
        - name: php-apache
          image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: php-apache
spec:
  ports:
    - port: 80
  selector:
    run: php-apache