apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  namespace: kube-system
spec:
  serviceAccountName: dev-sa
  containers:
    - name: sample-container
      image: chaitu1812/aws-cli
      command: ["sleep","10000000s"]