apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: my-destination-rule
  namespace: sample

spec:
  host: nginx-svc.sample.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
        app: nginx
        testing: ab
    - name: v2
      labels:
        version: v2
        app: nginx
        testing: ab