apiVersion: v1
kind: Pod
metadata:
  name: important-pod
spec:
  priorityClassName: high-priority
  containers:
    - name: my-app
      image: nginx
      resources:
        requests:
          cpu: 1
          memory: 560Mi
        limits:
          cpu: 2
          memory: 1Gi