apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
  namespace: default
spec:
  containers:
    - name: my-container
      image: alpine
      command: ["sleep","100000s"]
      volumeMounts:
        - name: secret-volume
          mountPath: "/tmp/secret-data"  # Files will appear here
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: sample1
        items:
          - key: key1
            path: sample1

