apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod2
  name: pod2
spec:
  automountServiceAccountToken: false
  serviceAccountName: default
  containers:
    - command:
        - sleep
        - "1000"
      image: chaitu1812/kubectl-cli
      name: pod2
      resources:
        requests:
          cpu: 100m
          memory: 125Mi
        limits:
          cpu: 150m
          memory: 200Mi
      securityContext:
        runAsUser: 10002
        runAsGroup: 10001
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL