apiVersion: v1
kind: Service
metadata:
  name: sample
  selector:
    app: nginx
  clusterIP: None
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  serviceName: sample
  template:
    metadata:
      app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web
              mountPath: /usr/share/nginx/html/
  volumeClaimTemplates:
      - metadata:
          name: web
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi




