apiVersion: v1
kind: Pod
metadata:
  name: oom
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: 50m
          memory: 2Mi
        limits:
          cpu: 100m
          memory: 2Mi
