apiVersion: v1
kind: Pod
metadata:
  name: tom
spec:
  containers:
    - name: tmocat
      image: tomcat:9.0.98-jre8
      resources:
        requests:
          cpu: 50m
          memory: 5Mi
        limits:
          cpu: 100m
          memory: 10Mi