apiVersion: v1
kind: Pod
metadata:
  name: tom
spec:
  containers:
    - name: c1
      image: alpine
      command: ["/bin/sh","-c"]
      args:
        - "echo 'This is chaithanya' > /name && sleep 10000s"
    - name: c2
      image: alpine
      command: ["/bin/sh","-c"]
      args:
        - "echo 'This is chaithanya' > /name && sleep 10000s"
      securityContext:
        readOnlyRootFilesystem: true


