apiVersion: v1
kind: Pod
metadata:
  name: tom
spec:
  containers:
    - name: tmocat
      image: alpine
      command: ["/bin/sh","-c"]
      args:
        - "echo 'This is chaithanya' > /name"
      securityContext:
        readOnlyRootFilesystem: true

