apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  shareProcessNamespace: true
  containers:
    - name: main
      image: chaitu1812/crash-loop
      resources:
        requests:
          cpu: 3
        limits:
          cpu: 4