apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  completions: 4
  activeDeadlineSeconds: 20
  template:
    spec:
      containers:
        - name: pi
          image: alpine
          command: ["sh","-c","sleep 10 && false"]
      restartPolicy: OnFailure