apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: pi
          image: alpine
          command: ["sleep","10"]
      restartPolicy: OnFailure