apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: pi
          image: alpine
          command: ["sh","-c","sleep 10 && false"]
      restartPolicy: OnFailure