apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  volumes:
    - name: vol
      hostPath:
        path: /tmp/vol
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: vol
          mountPath: /usr/share/nginx/html/
  initContainers:
    - name: init1
      image: alpine
      command: ["sh","-c"]
      restartPolicy: Never
      env:
        - name: pod_ip
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      args:
        - 'echo "This is init1 - ${pod_ip}" > /data/index.html; sleep 15 ; exit 1'
      volumeMounts:
        - name: vol
          mountPath: /data
    - name: init2
      image: alpine
      command: [ "sh","-c" ]
      env:
        - name: pod_ip
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      args:
        - 'echo "This is init2 - ${pod_ip}" >> /data/index.html; sleep 15'
      volumeMounts:
        - name: vol
          mountPath: /data