apiVersion: v1
kind: Pod
metadata:
  name: pod01
spec:
  volumes:
    - name: vol
      hostPath:
        path: /tmp/vol
  containers:
    - name: c1
      image: nginx
      volumeMounts:
        - name: vol
          mountPath: /usr/share/nginx/html/

    - name: c1
      image: alpine
      command: ["sh","-c"]
      args:
        - "while true; do echo This is $(date) > /data/index.html; sleep 1; done"
      volumeMounts:
        - name: vol
          mountPath: /data

