apiVersion: v1
kind: Pod
metadata:
  name: noooo
  namespace: istio
  labels:
    app: my-app
spec:
  containers:
    - name: my-app-container
      image: chaitu1812/debug
      command: ["sleep","100000s"]