---
apiVersion: v1
kind: Namespace
metadata:
  name: istio
  labels:
    istio-injection: enabled


---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: "istio-perrauth"
  namespace: "istio"
spec:
  mtls:
    mode: STRICT