apiVersion: v1
kind: Pod
metadata:
  name: no
  namespace: istio
  labels:
    app: my-app
  annotations:
    sidecar.istio.io/inject: "false"  # Disables Istio sidecar injection for this pod
spec:
  containers:
    - name: my-app-container
      image: chaitu1812/debug
      command: ["sleep","100000s"]