apiVersion: v1
kind: Pod
metadata:
  name: sample
  namespace: istio
  labels:
    app: nginx
spec:
  containers:
    - name: my-app-container
      image: chaitu1812/istio-methods
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: istio
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
