apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  secret-id:


---


apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: example
spec:
  provider:
    vault:
      server: "http://172.31.95.237:8200"
      path: "devops"
      version: "v2"
      auth:
        appRole:
          roleId: "fbcebb50-1ce1-15f7-c203-be64267156ed"
          secretRef:
            name: "my-secret"
            key: "secret-id"