apiVersion: v1
kind: ServiceAccount
metadata:
  name: example1
  namespace: sample
---
apiVersion: v1
kind: Pod
metadata:
  name: example1
  namespace: sample
spec:
  serviceAccountName: example1
  containers:
    - name: example1
      image: chaitu1812/debug
      command: ["sleep","1000000s"]