apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: strict-mlts
  namespace: sample
spec:
  mtls:
    mode: PERMISSIVE

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: strict-mtls1
  namespace: sample
spec:
  selector:
    matchLabels:
      app: nginx
  mtls:
    mode: STRICT