apiVersion: v1
kind: Pod
metadata:
  name: sample-pod1
  namespace: sample
  labels:
    app: nginx
    version: v1
spec:
  containers:
    - name: my-container1
      image: chaitu1812/istio-methods
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx1
  namespace: sample
  labels:
    app: my-app
spec:
  selector:
    app: nginx
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80