apiVersion: v1
kind: Pod
metadata:
  name: debug1
  namespace: sample
  labels:
    app: my-app
    version: v1
spec:
  containers:
    - name: debug1
      image: chaitu1812/debug
      command: ["sleep","100000s"]