apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  namespace: sample
  labels:
    app: my-app
    version: v1
spec:
  containers:
    - name: my-container
      image: chaitu1812/istio-methods
      ports:
        - containerPort: 80