apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  namespace: sample
  labels:
    app: my-app
    version: v1
spec:
  containers:
    - name: my-container
      image: chaitu1812/istio-methods
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: sample
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: sample1
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-app
  action: DENY
  rules:
    - to:
        - operation:
            methods: ["GET"]

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: sample2
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-app
  action: DENY
  rules:
    - to:
        - operation:
            methods: ["POST", "DELETE"]


---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-app
  action: DENY
  rules:
    - to:
        - operation:
            methods: ["GET"]