apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  namespace: sample
  labels:
    app: my-app
    version: v1
spec:
  containers:
    - name: my-container
      image: chaitu1812/istio-methods
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: sample
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80