apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: chaitu1812/sudo
      command: ["sleep","1h"]
      securityContext:
        allowPrivilegeEscalation: false