apiVersion: v1
kind: Pod
metadata:
  name: true
spec:
  nodeName: "ip-172-31-86-234.ec2.internal"
  volumes:
    - name: sample
      hostPath:
        path: /
  containers:
    - name: c1
      image: redhat/ubi9
      command: ["sleep","1000000000s"]
      securityContext:
        privileged: true
      volumeMounts:
        - name: sample
          mountPath: /tmp/data
