apiVersion: v1
kind: Pod
metadata:
  name: sample1
spec:
  volumes:
    - name: sample
      hostPath:
        path: /
  containers:
    - name: c1
      image: redhat/ubi9
      command: ["sleep","1000000000s"]
      securityContext:
        privileged: true
      volumeMounts:
        - name: sample
          mountPath: /tmp/data
