apiVersion: v1
kind: Pod
metadata:
  name: sudo
spec:
  containers:
    - name: c1
      image: chaitu1812/sudo
      command: ["sleep","1000000000s"]
      securityContext:
          capabilities:
            drop:
              - ALL



