apiVersion: v1
kind: Pod
metadata:
  name: ping-capability-pod
spec:
  containers:
    - name: ping-container
      image: alpine
      command: ["sleep","10000s"]
      securityContext:
        capabilities:   # Add capability for raw sockets (required for ping)
          drop:
            - ALL          # Drop all other capabilities for security