apiVersion: v1
kind: Pod
metadata:
  name: ping-capability-pod
spec:
  containers:
    - name: ping-container
      image: redhat/ubi9
      command: ["sleep","10000s"]
      securityContext:
        capabilities:
          add:
            - SYS_TIME
