apiVersion: v1
kind: Pod
metadata:
  name: pod01
spec:
  containers:
    - name: c1
      image: chaitu1812/netpol-rhel9
      command: ["sleep","1h"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod02
spec:
  containers:
    - name: c1
      image: chaitu1812/netpol-rhel9
      command: ["sleep","1h"]

