apiVersion: v1
kind: Pod
metadata:
  name: pod01
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: c1
      image: chaitu1812/sudo-user
      command: ["sleep","1h"]
      securityContext:
        capabilities:
          add: ["NET_ADMIN","SYS_TIME" ]




