apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          backoffLimit: 1
          containers:
            - name: hello
              image: alpine
              imagePullPolicy: IfNotPresent
              command:
                - "/bin/sh"
                - "-c"
                - "sleep 4 & exit 1"
          restartPolicy: Never

