apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: alpine
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - "sleep 10 & exit 1"
          restartPolicy: Never
