apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  ttlSecondsAfterFinished: 40
  template:
    spec:
      containers:
        - name: pi
          image: alpine
          command:
            - "sh"
            - "-c"
            - "sleep 10s"
      restartPolicy: Never
  backoffLimit: 1

