apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
        - name: pi
          image: alpine
          command: ["sleep","15s","&","exit 1"]
      restartPolicy: Never
  backoffLimit: 1

