apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  completions: 2
  activeDeadlineSeconds: 10
  template:
    spec:
      containers:
        - name: pi
          image: alpine
          command:
            - "sh"
            - "-c"
            - "sleep 50s"
      restartPolicy: Never
  backoffLimit: 1

