apiVersion: v1
kind: Pod
metadata:
  name: tom
spec:
  containers:
    - name: tomcat
      image: chaitu1812/debug
      command: ["sleep" ,"1000s"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000


---
apiVersion: v1
kind: Pod
metadata:
  name: tom1
spec:
  containers:
    - name: tomcat
      image: chaitu1812/debug
      command: ["sleep" ,"1000s"]
      securityContext:
        readOnlyRootFilesystem: true