
apiVersion: v1
kind: Pod
metadata:
  name: tom1
spec:
  containers:
    - name: tomcat
      image: chaitu1812/sudo-user
      command: ["sleep" ,"1000s"]
---

apiVersion: v1
kind: Pod
metadata:
  name: tom3
spec:
  containers:
    - name: tomcat
      image: chaitu1812/sudo-user
      command: ["sleep" ,"1000s"]
      securityContext:
        privileged: true