apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  initContainers:
    - name: init
      image: alpine
      command: ["sleep" ,"40s"]

  containers:
    - name: tomcat1
      image: chaitu1812/debug
      command: ["sleep" ,"1000s"]


