apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container-pod
spec:
  containers:
    - name: main-container
      image: nginx
    - name: setup-sidecar-container
      image: alpine
      command: ["sh", "-c", "while true; do echo 'Running setup tasks...'; sleep 10; done"]
      restartPolicy: Always