apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container-pod
spec:
  volumes:
    - name: my-emptydir
      emptyDir: {}
  containers:
    - name: sidecar-setup-container
      image: alpine
      command: ["sh", "-c", "echo 'Setting up'; sleep 40; echo 'Done setup'"]
      volumeMounts:
        - mountPath: /data
          name: my-emptydir
      lifecycle:
        postStart:
          exec:
            command: ["sh", "-c", "echo 'Cleaning up before termination------------' >> /data/1.txt"]
        preStop:
          exec:
            command: ["sh", "-c", "echo 'Cleaning up before termination------------' >> /data/2.txt"]
