apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container-pod
spec:
  containers:
    - name: main-container
      image: nginx
    - name: sidecar-setup-container
      image: alpine
      command: ["sh", "-c", "echo 'Setting up'; sleep 10; echo 'Done setup'"]
      lifecycle:
        postStart:
          exec:
            command: ["sh", "-c", "echo 'Sidecar started'"]
        preStop:
          exec:
            command: ["sh", "-c", "echo 'Cleaning up before termination'"]
