apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container-pod
spec:
  containers:
    - name: sidecar-setup-container
      image: alpine
      command: ["sh", "-c", "echo 'Setting up'; sleep 20; echo 'Done setup'"]
      lifecycle:
        postStart:
          exec:
            command: ["sh", "-c", "echo 'Sidecar started---------------------' ; sleep 20"]
        preStop:
          exec:
            command: ["sh", "-c", "echo 'Cleaning up before termination------------';sleep 20"]
